<form role="form" class="formLimit" method="post" enctype="application/x-www-form-urlencoded">
    <div class="form-group">
        <label >Nome Cliente:</label>
        <input type="text" class="form-control"   name="nome" value="<?php echo $this->data['data']['nome']; ?>"/>
    </div>
    <div class="form-group">
        <label >Login:</label>
        <input type="text" class="form-control"   name="login" value="<?php echo $this->data['data']['login']; ?>" />
    </div>
    <div class="form-group">
        <label >Senha:</label>
        <input type="text" class="form-control"   name="senha" value="<?php echo $this->data['data']['senha']; ?>"/>
    </div>
    <input type="hidden" name="id" value="<?php echo $this->data['data']['id']; ?>"/>
    <a href="/" class="btn btn-default">Voltar</a> <button type="submit" class="btn btn-primary">Enviar</button>
</form>