<form role="form" class="formLimit" method="post" enctype="application/x-www-form-urlencoded">
    <div class="form-group">
        <label >Nome Conexao:</label>
        <input type="text" class="form-control"   name="name" />
    </div>
    <div class="form-group">
        <label >Driver:</label>
        <select name="driver_id" class="form-control">
            <?php foreach($this->data['drivers'] as $d){ ?>
                <option value="<?php echo $d['id']; ?>"><?php echo $d['driver']; ?></option>
            <?php } ?>
        </select>
    </div>
    <div class="form-group">
        <label >Host:</label>
        <input type="text" class="form-control"   name="host"/>
    </div>
    <div class="form-group">
        <label >Porta:</label>
        <input type="text" class="form-control"   name="porta"/>
    </div>
    <div class="form-group">
        <label >DbName:</label>
        <input type="text" class="form-control"   name="dbname"/>
    </div>
    <div class="form-group">
        <label >User:</label>
        <input type="text" class="form-control"   name="user"/>
    </div>
    <div class="form-group">
        <label >Password:</label>
        <input type="text" class="form-control"   name="password"/>
    </div>
    <input type="hidden" name="cliente_id" value="<?php echo $this->data['cliente_id']; ?>"/>
    <a href="?pag=conexao&cliente_id=<?php echo $this->data['cliente_id']; ?>" class="btn btn-default">Voltar</a> <button type="submit" class="btn btn-primary">Enviar</button>
</form>