<html lang="en">
<head>
    <meta charset="utf-8">

    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="css/bootstrap-theme.min.css" rel="stylesheet">
    <link href="css/style.css" rel="stylesheet">


</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="index.php"><img src="img/zf2-logo.png" alt="Coletor Universal "/></a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="active"><a href="index.php">Clientes</a></li>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>
<div class="container">
    <?php
    require_once("../application/view/{$controller}/{$action}.phtml");

    ?>
    <hr>
    <footer>
        <p>&copy; 2014 - <?php echo date('Y') ?> by iDNA de vendas Ltd. All rights reserved.</p>
    </footer>
</div> <!-- /container -->

</body>
</html>

